### ISSUE TITLE
Double slash comment does not work correctly

### ISSUE THREAD

**Issue by chrishoage** [skozlovf/Sublime-GenericConfig#2]
I have a config file that uses `/* */` (which don't seem to be supported by generic config) and `//` (which from my understanding should be supported) 

For some reason `///` will syntax highlight the line as a comment but `//` will not. 

<img width="410" alt="screen shot 2016-05-06 at 2 07 48 pm" src="https://cloud.githubusercontent.com/assets/1056886/15086222/25140d0c-1394-11e6-8f46-17683b1cb5b6.png">

**Comment by skozlovf** [comment]
Yes, `/* */` is not supported. Maybe will add but only for one line comments.
What Sublime Text version you use?

**Comment by chrishoage** [comment]
Sublime Text 3 Dev Channel Build 3112

**Comment by skozlovf** [comment]
Ok, need to review syntax rules.
