### ISSUE TITLE
Multiline Comments

### ISSUE THREAD

**Issue by drone540** [skozlovf/Sublime-GenericConfig#4]
Can Multi line comments be added to this also?

I happened to run across a few conf files using multiline comment format syntax and was wondering if this could be added in also.

This Regex appears to be the best one for multiline comments: 
```regex
/\*[^*]*\*+(?:[^/*][^*]*\*+)*/
```
Example: https://regex101.com/r/dU5fO8/73
Source: https://stackoverflow.com/questions/13014947/regex-to-match-a-c-style-multiline-comment

**Comment by skozlovf** [comment]
Ok, will review soon.

**Comment by skozlovf** [comment]
It will take more time to review, super busy these days.
